backend:
  name: git-gateway
  branch: main

media_folder: "images/uploads"
public_folder: "/images/uploads"

collections:
  - name: "projekty"
    label: "Projekty"
    folder: "content/projekty"
    create: true
    slug: "{{slug}}"
    fields:
      - { label: "Tytuł", name: "title", widget: "string" }
      - { label: "Opis", name: "body", widget: "markdown" }
      - { label: "Zdjęcie", name: "thumbnail", widget: "image" }

  - name: "oferta"
    label: "Oferta"
    folder: "content/oferta"
    create: true
    slug: "{{slug}}"
    fields:
      - { label: "Tytuł", name: "title", widget: "string" }
      - { label: "Opis", name: "body", widget: "markdown" }

  - name: "strona-glowna"
    label: "Strona główna"
    files:
      - label: "Sekcja powitalna"
        name: "hero"
        file: "content/strona-glowna/hero.md"
        fields:
          - { label: "Nagłówek", name: "title", widget: "string" }
          - { label: "Opis", name: "body", widget: "markdown" }
          - { label: "Tło", name: "background", widget: "image" }
